In [2]:
# numpy         Numerical Calculations
# pandas        Data Exploration, cleaning, etc.
# matplotlib    Data Visualization
# seaborn       Advanced Data Visualization
# scipy         Scientific Calculations
# statistics    Statistical Functions
# sklearn       Machine Learning Algorithms
# tensorflow    Deep Learning Framework
# pytorch       Deep Learning Framework
# keras         Integrated with tensorflow
# cv2           Computer Vision , dealing with images colors and videos
# nltk          Natural Langauge Processing toolkit
# textblob      NLP

In [3]:
import numpy as np

In [4]:
# Arrays

In [5]:
arr1=np.array(5)

In [6]:
arr1

array(5)

In [7]:
arr2=np.array([2,5,4,7,3,6,9])

In [8]:
arr2

array([2, 5, 4, 7, 3, 6, 9])

In [9]:
arr3=np.array([[3,4,5],[2,5,7]])

In [10]:
arr3

array([[3, 4, 5],
       [2, 5, 7]])

In [11]:
arr4=np.array([[[2,3,4,5],[4,5,6,7]],[[1,2,3,4],[4,5,6,8]]])

In [12]:
arr4

array([[[2, 3, 4, 5],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 8]]])

In [13]:
# Attributes of numpy array
# -size   : total number of elements in the array
# -shape  : total number of elements in each axis of the array
# -ndim   : number of dimensions/axes on the array
# -dtype  : data type of the elements of the array

In [14]:
arr1

array(5)

In [15]:
arr1.size

1

In [16]:
arr1.shape

()

In [17]:
arr1.dtype

dtype('int64')

In [18]:
arr1.ndim

0

In [19]:
arr2

array([2, 5, 4, 7, 3, 6, 9])

In [20]:
arr2.size

7

In [21]:
arr2.shape

(7,)

In [22]:
arr2.dtype

dtype('int64')

In [23]:
arr2.ndim

1

In [24]:
arr3

array([[3, 4, 5],
       [2, 5, 7]])

In [25]:
arr3.size

6

In [26]:
arr3.shape

(2, 3)

In [27]:
arr3.dtype

dtype('int64')

In [28]:
arr3.ndim

2

In [29]:
arr4

array([[[2, 3, 4, 5],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 8]]])

In [30]:
arr4.size

16

In [31]:
arr4.shape

(2, 2, 4)

In [32]:
arr4.dtype

dtype('int64')

In [33]:
arr4.ndim

3

In [34]:
# int         :     int8, int16, int32, int64, uint8, uint16, uint32, etc.
# float       :     float16,float32, etc.
# str         :     object
# int8        :  -2^(n-1) to (2^(n-1))-1 : -2^7 to (2^7)-1 : -128 to 127
# uint8       :   0 to (2^n)-1 : 0 to (2^8)-1: 0 to 255
# int16       : -2^15 to (2^15)-1 : -32768 to 32767
# uint16      :   0 to (2^16)-1: 0 to 65535

In [35]:
arr5=np.array([[[2,3,4],[4,5,6]],[[1,2,3],[4,5,6]],[[2,4,5],[4,5,6]]])

In [36]:
arr5.shape

(3, 2, 3)

In [37]:
arr3

array([[3, 4, 5],
       [2, 5, 7]])

In [38]:
arr3.shape

(2, 3)

In [41]:
arr3=arr3.reshape(3,2)
arr3

array([[3, 4],
       [5, 2],
       [5, 7]])

In [ ]:
arr3.reshape(6,1)

In [ ]:
arr3.reshape(1,6)

In [ ]:
arr3.reshape(6)

In [ ]:
arr3.reshape(1,1,6)

In [ ]:
arr3.reshape(1,6,1)

In [ ]:
arr3.reshape(6,1,1)

In [ ]:
arr3.reshape(1,2,3)

In [ ]:
arr3.reshape(1,3,2)

In [ ]:
arr3.reshape(2,1,3)

In [ ]:
arr3.reshape(2,3,1)

In [ ]:
arr3.reshape(3,1,2)

In [ ]:
arr3.reshape(3,2,1)

In [57]:
arr3.reshape(3,1,2,1)

array([[[[3],
         [4]]],


       [[[5],
         [2]]],


       [[[5],
         [7]]]])

In [58]:
arr4

array([[[2, 3, 4, 5],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 8]]])

In [59]:
# how many different shapes can be found when reshaped in 1D and 2D

In [60]:
arr4.reshape(16)

array([2, 3, 4, 5, 4, 5, 6, 7, 1, 2, 3, 4, 4, 5, 6, 8])

In [61]:
arr4.reshape(16,1)

array([[2],
       [3],
       [4],
       [5],
       [4],
       [5],
       [6],
       [7],
       [1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6],
       [8]])

In [62]:
arr4.reshape(1,16)

array([[2, 3, 4, 5, 4, 5, 6, 7, 1, 2, 3, 4, 4, 5, 6, 8]])

In [63]:
arr4.reshape(2,8)

array([[2, 3, 4, 5, 4, 5, 6, 7],
       [1, 2, 3, 4, 4, 5, 6, 8]])

In [64]:
arr4.reshape(8,2)

array([[2, 3],
       [4, 5],
       [4, 5],
       [6, 7],
       [1, 2],
       [3, 4],
       [4, 5],
       [6, 8]])

In [65]:
arr4.reshape(4,4)

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 8]])

In [67]:
# Random module in numpy

In [74]:
np.random.randint(100)

93

In [81]:
np.random.randint(0,100,10)

array([41, 61, 10, 65,  9, 59, 18,  5, 82, 46])

In [100]:
otp=np.random.randint(0,10,6)
print(otp)

[9 3 4 2 6 5]


In [99]:
np.random.seed(13)
otp=np.random.randint(0,10,6)
print(otp)

[2 0 0 6 2 4]


In [104]:
np.random.seed(4)
a1=np.random.randint(0,10,10)
a1

array([7, 5, 1, 8, 7, 8, 2, 9, 7, 7])

In [105]:
np.unique(a1)

array([1, 2, 5, 7, 8, 9])

In [106]:
np.unique(a1,return_counts=True)

(array([1, 2, 5, 7, 8, 9]), array([1, 1, 1, 4, 2, 1]))

In [107]:
np.sum(a1)

61

In [108]:
np.product(a1)

13829760

In [109]:
np.mean(a1)

6.1

In [110]:
np.size(a1)

10

In [111]:
np.median(a1)

7.0

In [112]:
np.std(a1)

2.507987240796891

In [113]:
np.var(a1)

6.290000000000001

In [114]:
np.min(a1)

1

In [115]:
np.max(a1)

9

In [116]:
np.argmin(a1)

2

In [118]:
np.argmax(a1)

7

In [117]:
a1

array([7, 5, 1, 8, 7, 8, 2, 9, 7, 7])

In [124]:
np.random.seed(3)
a2=np.random.randint(0,20,8)
a2

array([10,  3,  8,  0, 19, 10, 11,  9])

In [125]:
a2.reshape(4,2)

array([[10,  3],
       [ 8,  0],
       [19, 10],
       [11,  9]])

In [126]:
np.random.seed(3)
a2=np.random.randint(0,20,(2,4))
a2

array([[10,  3,  8,  0],
       [19, 10, 11,  9]])

In [127]:
for i in range(0,5,1):
  print(i)

0
1
2
3
4


In [128]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [129]:
np.arange(12,36,3)

array([12, 15, 18, 21, 24, 27, 30, 33])

In [130]:
np.arange(43,12,-7)

array([43, 36, 29, 22, 15])